# Generated by Django 4.0.4 on 2022-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('re_name', models.CharField(max_length=100)),
                ('re_skill1', models.CharField(max_length=100)),
                ('re_skill2', models.CharField(max_length=100)),
                ('re_skill3', models.CharField(max_length=100)),
                ('re_skill4', models.CharField(max_length=100)),
                ('re_education1', models.CharField(max_length=100)),
                ('re_education2', models.CharField(max_length=100)),
                ('re_education3', models.CharField(max_length=100)),
                ('re_education4', models.CharField(max_length=100)),
                ('re_experience1', models.CharField(max_length=100)),
                ('re_experience2', models.CharField(max_length=100)),
                ('re_experience3', models.CharField(max_length=100)),
                ('re_experience4', models.CharField(max_length=100)),
                ('re_address', models.CharField(max_length=100)),
                ('re_phone', models.CharField(max_length=100)),
                ('re_email', models.CharField(max_length=100)),
                ('re_resume', models.ImageField(upload_to='app/static/media/resumedata')),
                ('re_image', models.ImageField(upload_to='app/static/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
