# Generated by Django 4.0.4 on 2022-06-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume1',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('re_about', models.CharField(max_length=250)),
                ('re_name', models.CharField(max_length=100)),
                ('re_education1', models.CharField(max_length=100)),
                ('re_education2', models.CharField(max_length=100)),
                ('re_education3', models.CharField(max_length=100)),
                ('re_education4', models.CharField(max_length=100)),
                ('re_experience1', models.CharField(max_length=100)),
                ('re_experience2', models.CharField(max_length=100)),
                ('re_experience3', models.CharField(max_length=100)),
                ('re_experience4', models.CharField(max_length=100)),
                ('re_address', models.CharField(max_length=100)),
                ('re_phone', models.CharField(max_length=100)),
                ('re_email', models.CharField(max_length=100)),
                ('re_resume', models.ImageField(upload_to='app/static/web/media/resumedata')),
                ('re_image', models.ImageField(upload_to='app/static/web/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume2',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('re_about', models.CharField(max_length=250)),
                ('re_name', models.CharField(max_length=100)),
                ('re_skill1', models.CharField(max_length=100)),
                ('re_skill2', models.CharField(max_length=100)),
                ('re_skill3', models.CharField(max_length=100)),
                ('re_skill4', models.CharField(max_length=100)),
                ('re_education1', models.CharField(max_length=100)),
                ('re_education2', models.CharField(max_length=100)),
                ('re_education3', models.CharField(max_length=100)),
                ('re_education4', models.CharField(max_length=100)),
                ('re_experience1', models.CharField(max_length=100)),
                ('re_experience2', models.CharField(max_length=100)),
                ('re_experience3', models.CharField(max_length=100)),
                ('re_experience4', models.CharField(max_length=100)),
                ('re_address', models.CharField(max_length=100)),
                ('re_phone', models.CharField(max_length=100)),
                ('re_email', models.CharField(max_length=100)),
                ('re_resume', models.ImageField(upload_to='app/static/web/media/resumedata')),
                ('re_image', models.ImageField(upload_to='app/static/web/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume3',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('re_about', models.CharField(max_length=250)),
                ('re_name', models.CharField(max_length=100)),
                ('re_skill1', models.CharField(max_length=100)),
                ('re_skill2', models.CharField(max_length=100)),
                ('re_skill3', models.CharField(max_length=100)),
                ('re_skill4', models.CharField(max_length=100)),
                ('re_education1', models.CharField(max_length=100)),
                ('re_education2', models.CharField(max_length=100)),
                ('re_education3', models.CharField(max_length=100)),
                ('re_education4', models.CharField(max_length=100)),
                ('re_address', models.CharField(max_length=100)),
                ('re_phone', models.CharField(max_length=100)),
                ('re_email', models.CharField(max_length=100)),
                ('re_resume', models.ImageField(upload_to='app/static/web/media/resumedata')),
                ('re_image', models.ImageField(upload_to='app/static/web/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
