# Generated by Django 4.0.4 on 2022-06-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visit1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit2',
            fields=[
                ('vi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vi_name', models.CharField(max_length=100)),
                ('vi_address', models.CharField(max_length=100)),
                ('vi_phone', models.CharField(max_length=100)),
                ('vi_phone1', models.CharField(max_length=100)),
                ('vi_email', models.CharField(max_length=100)),
                ('vi_image', models.ImageField(upload_to='app/static/web/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visit3',
            fields=[
                ('vi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vi_name', models.CharField(max_length=100)),
                ('vi_address', models.CharField(max_length=100)),
                ('vi_phone', models.CharField(max_length=100)),
                ('vi_phone1', models.CharField(max_length=100)),
                ('vi_email', models.CharField(max_length=100)),
                ('vi_image', models.ImageField(upload_to='app/static/web/media/images')),
                ('re_status', models.IntegerField(default=0)),
                ('re_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
