# Generated by Django 4.0.4 on 2022-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_visit2_visit3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation1',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('in_bride', models.CharField(max_length=100)),
                ('in_groom', models.CharField(max_length=100)),
                ('in_date', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('in_venue', models.CharField(max_length=100)),
                ('in_status', models.IntegerField(default=0)),
                ('in_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='visit1',
            old_name='re_created_by',
            new_name='vi_created_by',
        ),
        migrations.RenameField(
            model_name='visit1',
            old_name='re_status',
            new_name='vi_status',
        ),
        migrations.RenameField(
            model_name='visit2',
            old_name='re_created_by',
            new_name='vi_created_by',
        ),
        migrations.RenameField(
            model_name='visit2',
            old_name='re_status',
            new_name='vi_status',
        ),
        migrations.RenameField(
            model_name='visit3',
            old_name='re_created_by',
            new_name='vi_created_by',
        ),
        migrations.RenameField(
            model_name='visit3',
            old_name='re_status',
            new_name='vi_status',
        ),
    ]
