# Generated by Django 4.0.4 on 2022-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_invitation1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation2',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('in_bride', models.CharField(max_length=100)),
                ('in_groom', models.CharField(max_length=100)),
                ('in_date', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('in_venue', models.CharField(max_length=100)),
                ('in_status', models.IntegerField(default=0)),
                ('in_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation3',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('in_bride', models.CharField(max_length=100)),
                ('in_groom', models.CharField(max_length=100)),
                ('in_date', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('in_venue', models.CharField(max_length=100)),
                ('in_status', models.IntegerField(default=0)),
                ('in_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(max_length=100)),
                ('us_mobile', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_status', models.CharField(max_length=100)),
                ('us_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
