# Generated by Django 4.0.4 on 2022-06-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invitation2_invitation3_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('py_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('py_card_id', models.CharField(max_length=100)),
                ('py_user_name', models.CharField(default='', max_length=100)),
                ('py_user_email', models.CharField(max_length=100)),
                ('py_amount', models.CharField(max_length=100)),
                ('py_status', models.IntegerField(default=0)),
                ('py_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
