# Generated by Django 4.0.4 on 2022-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume1',
            name='re_skill1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume1',
            name='re_skill2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume1',
            name='re_skill3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume1',
            name='re_skill4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
