# Generated by Django 4.0.4 on 2022-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_resume1_re_skill1_resume1_re_skill2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation1',
            name='in_invitation_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invitation2',
            name='in_invitation_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invitation3',
            name='in_invitation_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
