# Generated by Django 4.0.4 on 2022-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invitation1_in_invitation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_status', models.IntegerField(default=0)),
                ('ad_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
