# Generated by Django 4.0.4 on 2022-06-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_adminmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWebsite',
            fields=[
                ('bw_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bw_unique_id', models.CharField(max_length=100)),
                ('bw_slimage1', models.FileField(upload_to='app/static/media/images')),
                ('bw_slimage2', models.FileField(upload_to='app/static/media/images')),
                ('bw_slimage3', models.FileField(upload_to='app/static/media/images')),
                ('bw_slimage4', models.FileField(upload_to='app/static/media/images')),
                ('bw_abimage1', models.FileField(upload_to='app/static/media/images')),
                ('bw_abimage2', models.FileField(upload_to='app/static/media/images')),
                ('bw_about', models.CharField(max_length=100)),
                ('bw_seimage1', models.FileField(upload_to='app/static/media/images')),
                ('bw_seimage2', models.FileField(upload_to='app/static/media/images')),
                ('bw_services', models.CharField(max_length=100)),
                ('bw_status', models.IntegerField(default=0)),
                ('bw_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWebsite',
            fields=[
                ('pw_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pw_unique_id', models.CharField(max_length=100)),
                ('pw_slimage1', models.FileField(upload_to='app/static/media/images')),
                ('pw_slimage2', models.FileField(upload_to='app/static/media/images')),
                ('pw_slimage3', models.FileField(upload_to='app/static/media/images')),
                ('pw_slimage4', models.FileField(upload_to='app/static/media/images')),
                ('pw_abimage1', models.FileField(upload_to='app/static/media/images')),
                ('pw_abimage2', models.FileField(upload_to='app/static/media/images')),
                ('pw_about', models.CharField(max_length=100)),
                ('pw_education', models.CharField(max_length=100)),
                ('pw_services', models.CharField(max_length=100)),
                ('pw_status', models.IntegerField(default=0)),
                ('pw_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
