# Generated by Django 4.0.4 on 2022-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_businesswebsite_personalwebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_abimage1',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_abimage2',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_seimage1',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_seimage2',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_services',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_slimage1',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_slimage2',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_slimage3',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='bw_slimage4',
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_designation1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_designation2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_designation3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_education1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_education2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_education3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_experience1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_experience2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_experience3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_experience_years',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_freelance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_service6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill6',
            field=models.CharField(default='', max_length=100),
        ),
    ]
