# Generated by Django 4.0.4 on 2022-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_businesswebsite_bw_abimage1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill1_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill2_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill3_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill4_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill5_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_skill6_per',
            field=models.CharField(default='', max_length=100),
        ),
    ]
