# Generated by Django 4.0.4 on 2022-06-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_businesswebsite_bw_skill1_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_abimage1',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_abimage2',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_education',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_services',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_slimage1',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_slimage2',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_slimage3',
        ),
        migrations.RemoveField(
            model_name='personalwebsite',
            name='pw_slimage4',
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_designation1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_designation2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_designation3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_education1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_education2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_education3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_experience1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_experience2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_experience3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_experience_years',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_freelance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_service6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill1_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill2_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill3_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill4_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill5_per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_skill6_per',
            field=models.CharField(default='', max_length=100),
        ),
    ]
