# Generated by Django 4.0.4 on 2022-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_bw_address_businesswebsite_bw_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_projects',
            field=models.CharField(default='', max_length=100),
        ),
    ]
