# Generated by Django 4.0.6 on 2022-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_businesswebsite_bw_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalwebsite',
            old_name='bw_company_description',
            new_name='pw_amount',
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_company_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
