# Generated by Django 4.0.6 on 2022-07-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_bw_company_description_personalwebsite_pw_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
