# Generated by Django 4.0.6 on 2022-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_businesswebsite_bw_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='bw_created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
