# Generated by Django 4.0.5 on 2022-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_businesswebsite_bw_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='us_secret_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
