# Generated by Django 4.0.6 on 2022-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_registration_us_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalwebsite',
            name='pw_image',
            field=models.ImageField(default='True', upload_to='app/static/media/images/'),
        ),
    ]
